// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQk3JZk46cCb7FqRH9zFwaSDvPMc_shAM',
    appId: '1:50149487978:web:df0b18b3e5d8561d2be113',
    messagingSenderId: '50149487978',
    projectId: 'issuesubmission-a8cc7',
    authDomain: 'issuesubmission-a8cc7.firebaseapp.com',
    storageBucket: 'issuesubmission-a8cc7.firebasestorage.app',
    measurementId: 'G-Q9E6TX1V4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNCLnGfqD1q7k7ULrYPlfnRNjOQOAmOFA',
    appId: '1:50149487978:android:e9ef02d3c974529c2be113',
    messagingSenderId: '50149487978',
    projectId: 'issuesubmission-a8cc7',
    storageBucket: 'issuesubmission-a8cc7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxaq5SeeVcK1ykUpKC1qIEuWkVB3hD4rQ',
    appId: '1:50149487978:ios:1d0e792e014848c72be113',
    messagingSenderId: '50149487978',
    projectId: 'issuesubmission-a8cc7',
    storageBucket: 'issuesubmission-a8cc7.firebasestorage.app',
    iosBundleId: 'com.example.issueSubmissionInterface',
  );
}
